//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Medusa.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MedusaDocumentTYPE          130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDI_MODEL_RESVIEW               164
#define IDB_FILE_VIEW_24                176
#define IDB_MODEL_RESVIEW               176
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_CAPTIONBAR           295
#define IDS_EDIT_MENU                   306
#define IDR_SCENEPLACEMENT              311
#define IDR_MODLRESVIEW                 312
#define IDR_POPUP_MODELRESVIEW          313
#define IDR_SCENETREEVIEW               313
#define IDR_POPUP_SCENE_TREEVIEW        314
#define IDB_MODEL_RESVIEW1              314
#define IDB_SCENE_TREEVIEW              314
#define IDR_CAMERAVIEW                  315
#define IDD_INSERT_NODE                 316
#define IDC_EDIT_FILENAME               1000
#define IDC_CB_MATERIAL                 1001
#define IDC_CB_EFFECT                   1002
#define IDC_CB_NODETYPE                 1003
#define IDC_POS_X                       1004
#define IDC_POS_Y                       1005
#define IDC_POS_Z                       1006
#define IDC_SCALE_X                     1007
#define IDC_SCALE_Y                     1008
#define IDC_SCALE_Z                     1009
#define IDC_ROT_X                       1010
#define IDC_ROT_Y                       1011
#define IDC_ROT_Z                       1012
#define IDC_EDIT12                      1013
#define IDC_ROT_ANGLE                   1013
#define IDC_CB_EFFECT2                  1014
#define IDC_CB_ENTITIY_TYPE             1014
#define IDC_EDIT1                       1015
#define IDC_TEXT_NODENAME               1015
#define ID_VIEW_PROPERTIESWND           1150
#define IDI_SHELLTREE                   1169
#define IDI_SCENE_TREEVIEW              1170
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BTN_SCENE_OP_MOVE            32771
#define ID_BTN_SCENE_OP_ROTATE          32772
#define ID_BTN_REFLESH                  32773
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_32776                        32776
#define ID_MRV_INSERT                   32777
#define ID_MODELOPERATOR_32778          32778
#define IDR                             32779
#define ID_MRV_PROPERTIES               32780
#define ID_STV_COMPILE                  32781
#define ID_STV_DELETE_NODE              32782
#define ID_MODELOPERATOR_INSERTNODE     32783
#define ID_STV_INSERTNODE               32784
#define ID_BTN_TOPCAMERA                32785
#define ID_BTN_FRONTCAMERA              32786
#define ID_MODELOPERATOR_REFLESHLIB     32787
#define ID_32788                        32788
#define ID_32789                        32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
