//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XEvolMaxExporter.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_PARAMS                      2
#define IDD_PANEL                       9
#define IDR_HTML_MAINDLG                2000
#define IDC_TREE1                       2002
#define IDC_NODE_TREE                   2002
#define IDD_NODE_TREE                   2003
#define IDC_BUTTON1                     2003
#define IDB_VIEWNODE                    2003
#define IDC_MODIFMESH_INFO              2003
#define IDC_MESH_PROP                   2003
#define IDD_NODE_VIEW                   2004
#define IDC_BUTTON2                     2004
#define IDC_EXPORT_STATICMODEL          2004
#define IDB_VIEWNODE2                   2004
#define IDC_BUTTON3                     2005
#define IDI_EVOL                        2005
#define IDB_ACTION_SAVE                 2005
#define IDC_BUTTON4                     2006
#define IDB_NODE_TYPE_BITMAP            2006
#define IDB_ACTION_LOAD                 2006
#define IDC_BUTTON5                     2007
#define IDD_STATICMESH_EXPORT           2007
#define IDC_EXPORT_FRAMEANI_MODEL       2007
#define IDB_VIEWNODE5                   2007
#define IDC_BUTTON6                     2008
#define IDD_MESH_PROPERTY               2008
#define IDB_VIEWNODE6                   2008
#define IDC_BUTTON7                     2009
#define IDD_DIALOG1                     2009
#define IDD_LOGTEXTDLG                  2009
#define IDB_VIEWNODE7                   2009
#define IDC_BUTTON8                     2010
#define IDD_FRAMEANI_MODEL_EXPORT       2010
#define IDB_VIEWNODE8                   2010
#define IDC_BUTTON9                     2011
#define IDD_FRAMEANI_CHARACTOR_EXPORTOR 2011
#define IDC_BUTTON10                    2012
#define IDD_SKELETON_DLG                2012
#define IDC_BUTTON11                    2013
#define IDC_CONFIRMSCENE                2013
#define IDD_SKELETON_MODEL_EXPROT_DLG   2013
#define IDC_BUTTON12                    2014
#define IDC_VIEWROOTSCENE_NODE          2014
#define IDD_SKELETON_ACTION_EXP         2014
#define IDC_IS_EXPORT_TO_PACKAGE        2015
#define IDC_BUTTON13                    2015
#define IDC_EXPORT_SKIN                 2015
#define IDD_BONES_GROUP                 2015
#define IDC_MESHLIST                    2016
#define IDC_IS_EXPORT_ASCII             2016
#define IDC_BUTTON14                    2016
#define IDC_EXPORT_SKELETON_MODEL       2016
#define IDD_BONE_GROUP_NAME             2016
#define IDT_UVLAYER                     2017
#define IDC_SETBONEID                   2017
#define IDD_SKINGROUP_DLG               2017
#define IDC_HASDIFFUSE                  2018
#define IDC_SET_SKELETON                2018
#define IDD_WATERMESH                   2018
#define IDC_HASTANGETSPACE              2019
#define IDC_BUTTON15                    2019
#define IDC_EXPORT_SKIN2                2019
#define IDC_EXPORT_ACTION               2019
#define IDD_MESH_EXPORTER               2019
#define IDC_HASNORMAL                   2020
#define IDC_SET_SKELETON2               2020
#define IDC_EXPORT_MESH                 2020
#define IDT_MODEL_NAME                  2021
#define IDC_SET_SKIN_GROUP              2021
#define IDC_LOGTEXT                     2022
#define IDC_SET_BONES_GROUP             2022
#define IDC_LIST1                       2023
#define IDC_CHECK1                      2024
#define IDC_EXPORT_ACTION_BACTH         2024
#define IDC_CHECK2                      2025
#define IDC_BUTTON17                    2025
#define IDC_EDIT1                       2026
#define IDC_BUTTON18                    2026
#define IDC_EDIT2                       2027
#define IDC_EXPORT_WATER_MESH           2027
#define IDC_EDIT3                       2028
#define IDC_EDIT4                       2029
#define IDC_EDIT5                       2030
#define IDC_EDIT8                       2031
#define IDC_EXPORT_TO_PACKAGE           2031
#define IDC_PACKAGE_PATH                2032
#define IDC_EDIT7                       2033
#define IDC_EXPORT_TEXTMODE             2033
#define IDC_EXPTEXTMODE                 2033
#define IDC_TEXTURECOOR_ANI             2034
#define IDC_POSITION_ANI                2035
#define IDC_DUARING_TIME                2036
#define IDC_FIRST_FRAME                 2037
#define IDC_LAST_FRAME                  2038
#define IDC_SCALE_FACTOR                2039
#define IDT_ACTION_NAME                 2040
#define IDB_ACTION_ADD                  2041
#define IDB_ACTION_REMOVE               2042
#define IDB_EXPORT                      2043
#define IDB_CANCEL                      2044
#define IDB_CANCEL_EXPORT               2044
#define IDL_ACTION_LIST                 2045
#define IDB_MESH_PROPERTY               2047
#define IDB_ACTION_SET                  2048
#define IDB_FINISH_SETUP                2048
#define IDB_MESH_PROPERTY3              2049
#define IDC_BUSE_BEFORESKELETON_BIND    2049
#define IDC_BUSE_BEFORESKELETON_BIND2   2050
#define IDC_CALCINITPOS_MYSEF           2050
#define IDC_CREATE_GROUP                2050
#define IDC_ASSIGN_GROUP                2051
#define IDB_EXPORT2                     2051
#define IDC_BUSE_BEFORESKELETON_BIND3   2052
#define IDC_EXPORT_VERTEX_SHELL         2052
#define IDC_GROUP_NAME                  2052
#define IDC_DUMP_TO_FILE                2052
#define IDC_VIEW_GROUP                  2053
#define IDB_EXPORT3                     2053
#define IDB_SET_SKELETON                2053
#define IDC_INVERT_V_COORD              2053
#define IDC_VIEW_GROUP2                 2054
#define IDC_ALL_BONES                   2054
#define IDC_INVERT_V_COORD2             2054
#define IDC_INVERT_YZ_COORD             2054
#define IDC_DEL_SKINGROUP               2055
#define IDC_ALL_BONES2                  2055
#define IDC_ADD_BONES                   2055
#define IDC_CREATE_SKINGROUP            2056
#define IDC_CREATE_SKINGROUP2           2057
#define IDC_REFLESH                     2057
#define IDC_ADD_BONE_H                  2057
#define IDC_ALL_NODES                   2058
#define IDC_FMODELSCALE                 2059
#define IDC_UTILE                       2060
#define IDC_VTILE                       2061
#define IDB_SAVE_MESH                   2062
#define IDC_FPS                         2063
#define IDC_EXPORT_TO_SIGNLE            2064
#define IDC_COMBO1                      2065
#define IDC_COMPRESS_RATIO              2065
#define IDC_EXPORT_TO_SIGNLE2           2065
#define IDC_EXPORT_KEYFRAME             2065

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2021
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2066
#define _APS_NEXT_SYMED_VALUE           2001
#endif
#endif
