#ifndef _XEVOL3D_EX_PCH_
#define _XEVOL3D_EX_PCH_
#ifdef _WIN32
#include <windows.h>
#endif
#include <string>
#include <fstream>
#include <map>
#include <vector>
#include <set>
#include <stack>
#include <deque>
#include <new>
#include <algorithm>
#include <stdlib.h>
#include <stdio.h>
#include <memory.h>
#include <iostream>
#include <math.h>
#include <assert.h>
#include "xcomdoc/xdocfstream.h"
#include "RenderApi/xRenderApi.h"
#include "RenderApi/xRenderApiImp.h"
#include "BaseLib/xStringHash.h"
#include "RenderApi/xShaderManager.h"
#include "RenderApi/xBaseShader.h"
#include "RenderApi/xRenderStateObjManager.h"
#include "RenderApi/xRenderApiManager.h"
#include "RenderApi/xRenderView.h"
#include "RenderApi/xBaseTexture.h"
#include "BaseLib/xI18N.h"
#include "BaseLib/xBaseMath.h"
#include "OperationSys/xOperationSys.h"
#include "BaseLib/xEvol3DBaseInc.h"
#include "Application/xPluginMgr.h"
#include "BaseLib/xStringHash.h"
#include "xModel/xCoreMeshMgr.h"
#include "xModel/xBaseModelMgr.h"
#include "xModel/xCoreMesh.h"
#include "xModel/xBaseModel.h"
#endif